source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-paginate"
gem "jekyll-spaceship"
gem "webrick"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "ostruct"
